included: # paths to include during linting. `--path` is ignored if present.
  - Common
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

line_length:
  warning: 240
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

disabled_rules:
  - force_cast
  - force_try
  - function_body_length
  - nesting
  - todo
  - type_body_length
  - type_name
  - identifier_name
file_length:
  warning: 500
variable_name_max_length:
  warning: 45
  error: 60